"use client";

import { ScrollReveal } from "@/components/ui/scroll-reveal";
import { GlassCard } from "@/components/ui/glass-card";
import { Search, Sparkles, Play } from "lucide-react";
import { motion } from "framer-motion";
import Image from "next/image";
import { tracks } from "@/lib/data/mock";
import { NeonButton } from "@/components/ui/neon-button";
import { usePlayer } from "@/lib/player/player-context";

export default function ExplorePage() {
  const { play } = usePlayer();

  return (
    <div className="space-y-10">
      <ScrollReveal>
        <div className="pt-4">
          <h1 className="font-[var(--font-grotesk)] text-5xl md:text-6xl font-semibold tracking-tight">
            <span className="text-white">Discover your next</span>{" "}
            <span className="text-gradient">sound.</span>
          </h1>

          <div className="mt-6 glass-strong rounded-2xl border border-white/10 px-4 py-3 flex items-center gap-3 max-w-[720px]">
            <Search className="h-4 w-4 text-white/60" />
            <input
              className="w-full bg-transparent outline-none text-sm placeholder:text-white/45"
              placeholder="Find music for coding, focus, or a specific mood..."
            />
            <div className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 bg-white/5 text-white/60 text-xs">
              ⌘K
            </div>
          </div>
        </div>
      </ScrollReveal>

      <div className="grid gap-6 lg:grid-cols-3">
        <ScrollReveal>
          <div className="lg:col-span-2">
            <GlassCard strong className="relative overflow-hidden p-8 min-h-[260px]">
              <div className="absolute inset-0 opacity-60" style={{ background: "radial-gradient(900px 420px at 10% 20%, rgba(155,77,255,0.22), transparent 60%), radial-gradient(700px 420px at 70% 30%, rgba(94,234,212,0.12), transparent 60%)" }} />
              <div className="relative">
                <div className="flex items-center gap-2 text-[11px] tracking-[0.25em] uppercase text-white/50">
                  <span className="rounded-md bg-pink/20 px-2 py-1 text-pink">Live</span>
                  Neural Stream
                </div>
                <div className="mt-3 font-[var(--font-grotesk)] text-4xl md:text-5xl font-semibold">
                  Neural Techno v4.2
                </div>
                <p className="mt-3 max-w-md text-sm text-white/70">
                  Real-time evolving beats generated by the Auralis core engine—personalized to your
                  current focus pattern.
                </p>
                <NeonButton className="mt-6 h-11 px-6" onClick={() => play(tracks[0])}>
                  <Play className="h-4 w-4" />
                  Listen Now
                </NeonButton>

                <motion.div
                  className="pointer-events-none absolute right-6 top-6 h-28 w-28 rounded-full"
                  animate={{ rotate: 360 }}
                  transition={{ duration: 18, repeat: Infinity, ease: "linear" }}
                  style={{ background: "conic-gradient(from 90deg, rgba(155,77,255,0.9), rgba(255,122,198,0.7), rgba(94,234,212,0.6), rgba(155,77,255,0.9))", filter: "blur(1px)" }}
                />
              </div>
            </GlassCard>
          </div>
        </ScrollReveal>

        <div className="grid gap-6">
          {[
            { title: "Cyberpunk", sub: "2.4k listeners", accent: "bg-[rgba(155,77,255,0.35)]" },
            { title: "Ambient Intelligence", sub: "Curated for focus", accent: "bg-white/5" },
            { title: "Deep Focus", sub: "80 tracks", accent: "bg-white/5" },
            { title: "Infinite Lo‑Fi", sub: "24/7 AI-generated chill", accent: "bg-[rgba(255,122,198,0.18)]" }
          ].map((c, idx) => (
            <ScrollReveal key={c.title} delay={0.05 + idx * 0.03}>
              <GlassCard strong className={`p-6 ${c.accent}`}>
                <div className="flex items-start justify-between">
                  <div>
                    <div className="text-lg font-semibold">{c.title}</div>
                    <div className="mt-1 text-sm text-muted">{c.sub}</div>
                  </div>
                  <Sparkles className="h-5 w-5 text-neon" />
                </div>
              </GlassCard>
            </ScrollReveal>
          ))}
        </div>
      </div>

      <ScrollReveal>
        <div className="flex items-end justify-between">
          <div>
            <div className="font-[var(--font-grotesk)] text-3xl font-semibold">Mood‑Matching Playlists</div>
            <div className="text-sm text-muted">AI‑curated soundscapes for every state of mind.</div>
          </div>
          <button className="text-sm text-neon hover:text-white">View All →</button>
        </div>
      </ScrollReveal>

      <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6">
        {tracks.map((t, idx) => (
          <ScrollReveal key={t.id} delay={0.02 * idx}>
            <button
              onClick={() => play(t)}
              className="group text-left"
            >
              <div className="relative aspect-[4/3] overflow-hidden rounded-2xl border border-white/10 bg-white/5">
                <Image src={t.cover} alt={t.title} fill className="object-cover transition duration-300 group-hover:scale-[1.03]" />
              </div>
              <div className="mt-2 text-sm font-semibold truncate">{t.title}</div>
              <div className="text-xs text-muted truncate">{t.mood.label}</div>
            </button>
          </ScrollReveal>
        ))}
      </div>
    </div>
  );
}
